Before you turn this problem in, make sure everything runs as expected. First, **restart the kernel** (in the menubar, select Kernel$\rightarrow$Restart) and then **run all cells** (in the menubar, select Cell$\rightarrow$Run All).

Make sure you fill in any place that says `YOUR CODE HERE` or "YOUR ANSWER HERE".

START WITH ENTERING **YOUR NAME AND STUDENT ID** (DO NOT PUT SOME RANDOM TEXT HERE!!).

Enter also the name of your **collaborator AND STUDENT ID** below.

The first student name (with ID) should submit in Canvas. NOT the colloborator.

In [2]:
FULL_NAME = "Sasha van der Linden"
ID = "14014297"
COLLABORATOR = "Dave van Wijk"
ID2 = "14527820"

In [3]:
assert ID != ""


---

<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#Introduction" data-toc-modified-id="Introduction-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>Introduction</a></span></li><li><span><a href="#Array-Calculations-and-Indexing" data-toc-modified-id="Array-Calculations-and-Indexing-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>Array Calculations and Indexing</a></span></li><li><span><a href="#Views-on-Arrays" data-toc-modified-id="Views-on-Arrays-3"><span class="toc-item-num">3&nbsp;&nbsp;</span>Views on Arrays</a></span></li><li><span><a href="#Tricks-with-Arrays" data-toc-modified-id="Tricks-with-Arrays-4"><span class="toc-item-num">4&nbsp;&nbsp;</span>Tricks with Arrays</a></span></li><li><span><a href="#Data-Matrix-and-Target-Vector" data-toc-modified-id="Data-Matrix-and-Target-Vector-5"><span class="toc-item-num">5&nbsp;&nbsp;</span>Data Matrix and Target Vector</a></span></li><li><span><a href="#Linear-Algebra" data-toc-modified-id="Linear-Algebra-6"><span class="toc-item-num">6&nbsp;&nbsp;</span>Linear Algebra</a></span></li></ul></div>

# INF-SR: LabExercise Numpy

In [4]:
import numpy as np
import matplotlib.pyplot as plt
import sys
if sys.version_info[0] < 3:
    raise Exception("Must be using Python 3")

## Introduction
$\newcommand{\v}[1]{{\mathbf #1}}$

In machine learning we are dealing with massive amounts of data. Data most often organised in tables. When all data elements in a table are of the same datatype (like an integer or a floating point number) the table can be represented with a homogeneous array.

Languages that are optimally suited for programming with data are therefore equipped with array data types that are integral part of the language. Although arrays look a lot like python lists they are not as shown in the following code.

In [ ]:
a = np.array([1, 2, 3])
print(type(a))

In [ ]:
print(a)

In [ ]:
b = [1, 2, 3]
print(b)

In [ ]:
print(a+a)

In [ ]:
print(b+b)

Both lists and arrays are so called iterables in Python, therefor constructions like the following are possible:

In [ ]:
for element in a:
    print(element)

In [ ]:
for element in b:
    print(element)

The nice thing about Numpy arrays is that it allows you to manipulate the data in arrays without writing explicit loops. For instance look at the addition of all elements in an array:

In [12]:
a = np.random.rand(65536)

In [ ]:
print(a)
print(a.shape)

In [ ]:
def loopsum(a):
    sum = 0
    for v in a:
        sum += v
    return sum

%timeit loopsum(a)
%timeit np.sum(a)

So the explicit loop sum function in python takes milliseconds versus microseconds for the numpy version. That is many times slower for the explicit loop version.

So be aware in this course to use build-in Numpy tools to manipulate and calculate with arrays.

There are many python/numpy tutorials available like this one http://cs231n.github.io/python-numpy-tutorial/.

<span style="color:red">**Please open up a numpy manual or tutorial and only then use the exercises below to test your knowledge on numpy**</span>


## Array Calculations and Indexing

First we define some array to work with. By explicitly setting the seed the random number generator will always return the same 'random' numbers... (so i know the answers)

In [ ]:
np.random.seed(99283)

A = np.random.randint(1,10, size=(8,5))
print("A = ", A)

B = np.random.randint(1,10, size=(8,5))
print("B = ", B)

C = np.random.randint(1, 10, size=(128,))
print("C = ", C)

Write two functions: one to calculate the elementwise sum of A and B and another one to calculate the *elementwise* product of A and B. You are not allowed to use loops over the elements in the array.

In [16]:
def sumArrays(a, b):
    return a + b

In [17]:
# Check that functions are correct
assert np.all(sumArrays(A,B) == \
np.array([[17,  8,  6,  7, 14],
       [16, 14,  7,  6,  9],
       [16,  9,  6,  9, 11],
       [ 9, 12, 12, 11, 11],
       [12,  8,  8, 12,  8],
       [ 9, 14, 10,  7,  9],
       [18,  2, 13, 13,  9],
       [12, 14, 12, 13,  5]]))

assert np.all(sumArrays(A,-A) == np.zeros_like(A))


In [22]:
def mulArrays(a, b):
    return a * b

In [23]:
assert np.all(mulArrays(A,B) == \
np.array([[72, 15,  8,  6, 48],
       [63, 49,  6,  8, 18],
       [64, 20,  8, 20, 18],
       [14, 32, 32, 28, 30],
       [32, 12, 15, 35, 12],
       [ 8, 48, 16, 12,  8],
       [81,  1, 40, 36,  8],
       [27, 45, 35, 36,  6]]))
assert np.all(mulArrays(B, 1/B) == np.ones_like(B))

Calculate the mean of all elements in an array *without* using the mean or average function from numpy.

In [63]:
def meanArray(a):
    return a.sum() / a.size

In [64]:
assert meanArray(A) == np.mean(A) # the np.mean function that you can't use
assert meanArray(B) == np.mean(B)
assert np.allclose(meanArray(B/np.mean(B)), 1)

Calculate the standard deviation of all elements in an array *without* using the var or std functions from numpy.

In [69]:
def stdArray(a):
    mean = meanArray(a)
    total = 0
    for i in a:
        total += sum((i - mean) ** 2)
    return (total / a.size) ** 0.5


In [70]:
assert np.allclose(stdArray(A), np.std(A))
assert np.allclose(stdArray(B), np.std(B))

From C select the elements C[0], C[2], C[4], ... and sum all these

In [77]:
def sumEven(a):
    return a[::2].sum()

In [78]:
assert 328 == sumEven(C)

Select the first 32 elements from array C:

In [81]:
def selectFirst32(a):
    return a[:32]

In [82]:
assert all(selectFirst32(C) == \
           np.array([6, 5, 4, 5, 9, 8, 8, 4, 
                     2, 7, 8, 4, 1, 8, 9, 3, 
                     1, 1, 3, 3, 3, 7, 9, 4, 
                     8, 4, 3, 8, 1, 5, 3, 1]))

Select all elements from C that are not equal to 8. This can be done without explicit loops using the concept of **logical indexing** (see the numpy documentation for this).

In [87]:
def isnot8(a):
    return a[a != 8]

In [88]:
correct_answer = np.array([6, 5, 4, 5, 9, 4, 2, 7, 4, 1, 9, 3, 1, 1, 3, 3, 3, 7, 9, 4, 4, 3,
       1, 5, 3, 1, 3, 9, 7, 7, 9, 3, 4, 4, 7, 6, 2, 9, 1, 2, 9, 2, 3, 9,
       1, 6, 5, 9, 5, 6, 7, 5, 5, 3, 9, 3, 9, 3, 3, 5, 6, 5, 6, 9, 5, 2,
       1, 5, 6, 4, 3, 3, 3, 6, 9, 3, 4, 2, 2, 3, 1, 3, 2, 9, 4, 2, 5, 4,
       3, 7, 5, 6, 6, 7, 5, 2, 2, 3, 3, 3, 9, 4, 9, 3, 7, 5, 6, 9, 6, 7,
       6, 9])
assert np.all(correct_answer == isnot8(C))

Now select all rows from A that do not start with an 8

In [91]:
def notstart8(a):
    return a[a[:,0] != 8]

In [92]:
assert np.all(notstart8(A) == \
           np.array([[9, 7, 6, 2, 3],
                    [2, 4, 8, 4, 6],
                    [4, 6, 3, 7, 6],
                    [9, 1, 5, 9, 8],
                    [9, 9, 5, 9, 2]]))

Now select all rows that do not contain any 8

In [105]:
def notany8(a):
    return a[np.all(a != 8, axis=1)]

In [106]:
assert np.all(notany8(A) == np.array([[9, 7, 6, 2, 3],
       [4, 6, 3, 7, 6],
       [9, 9, 5, 9, 2]]))

Reverse the order of the columns in array B:

In [120]:
def reverse_colums(a):
    return a[:,::-1]

In [121]:
assert np.all(reverse_colums(B) == np.array([[6, 6, 4, 3, 9],
       [6, 4, 1, 7, 7],
       [2, 4, 2, 5, 8],
       [5, 7, 4, 8, 7],
       [2, 5, 5, 2, 8],
       [1, 4, 2, 6, 1],
       [1, 4, 8, 1, 9],
       [3, 4, 7, 5, 3]]))

Array indexing is probably one of the most difficult subjects of programming with numpy in an efficient way. Let A be a numpy ndarray (n-dimensional array) then A[obj] is an indexing operation on array A. It depends on the value and type of obj what type of indexing is used. There are really three types of indexing…



## Views on Arrays

Most often when you need arrays in programming, those arrays tend to be very large. Think of images with millions of pixels in it. Thus when calculating with arrays you don't want to make unnescessary copies of arrays. Numpy (thinks it) is very clever in circumventing the need of making copies of arrays. But the cleverness of numpy can bite you in the tail when your are not aware of what is going on.

In [122]:
AA = A.copy() # to be sure and not mess with A itself 
              # we start by explicitly making a copy 
print(AA)

[[8 5 2 1 8]
 [9 7 6 2 3]
 [8 4 4 5 9]
 [2 4 8 4 6]
 [4 6 3 7 6]
 [8 8 8 3 8]
 [9 1 5 9 8]
 [9 9 5 9 2]]


Next we select a subset of array AA and assign a new value to all elements in that smaller array.

In [123]:
AA2 = AA[::2,::2]
print(AA2)

[[8 2 8]
 [8 4 9]
 [4 3 6]
 [9 5 8]]


In [124]:
AA2[:,:] = 999
print(AA2)

[[999 999 999]
 [999 999 999]
 [999 999 999]
 [999 999 999]]


But lo and behold when we print the larger matrix AA:

In [125]:
print(AA)

[[999   5 999   1 999]
 [  9   7   6   2   3]
 [999   4 999   5 999]
 [  2   4   8   4   6]
 [999   6 999   7 999]
 [  8   8   8   3   8]
 [999   1 999   9 999]
 [  9   9   5   9   2]]


Evidently AA2 is still refering to the same data elements as AA. We say that AA2 provides a new **view on array AA**. The new view can be of different shape (as it is here). But remember that a view still points to the same data as the array on which it is view.

The rules Numpy uses when it doesn't and when it does make a copy of the data are not trivial. 

Be sure to keep this phenomenon in the back of your mind when confronted with a nasty bug in your code.

Slicing, indexing and views on arrays can be quite complex. Please read the documentation. Also note that even the Numpy documentation suggests to avoid the use of the `as_strided` function...

Below a way to collect the values of sliding window of three elements. C10_3 is an array with 3 consequtive values of C10 in a column. The nice thing about it is that it is just a view on C10 and thus although we 'see' 24 values in the C10_3 array they are really refering to the 10 values in C10.

In [126]:
from numpy.lib.stride_tricks import as_strided

C10 = C[:10].copy() # i don't want to change C
print(C10)
C10_3 = as_strided(C10, (3,8), (8,8))
print(C10_3)
C10[4] = 99
print(C10_3)
print(C10.dtype)

[6 5 4 5 9 8 8 4 2 7]
[[6 5 4 5 9 8 8 4]
 [5 4 5 9 8 8 4 2]
 [4 5 9 8 8 4 2 7]]
[[ 6  5  4  5 99  8  8  4]
 [ 5  4  5 99  8  8  4  2]
 [ 4  5 99  8  8  4  2  7]]
int64


Now what happens when we change the datatype of C10?

In [127]:
C10 = C[:10].copy() # i don't want to change C
C10 = C10.astype(np.int32)
print(C10)
print(C10.dtype)
C10_3 = as_strided(C10, (3,8), (8,8))
print(C10_3)

[6 5 4 5 9 8 8 4 2 7]
int32
[[         6          4          9          8          2        673
           0          0]
 [         4          9          8          2        673          0
           0          0]
 [         9          8          2        673          0          0
           0 -995356992]]


Probably not what you expected to happen... Again showing that working with strides of arrays is not easy (and dependent on the datatype... strides are specified in bytes!)

Note: the above trick with strides is not what you are expected to be able to reproduce and use in this course.

## Tricks with Arrays

Given the array C of shape (128,) make it into an array of shape (128,1). You can do that with the reshape method or with the use of the 'newaxis' index.

In [130]:
def vector2array(a):
    return a[:,np.newaxis]

In [131]:
assert vector2array(C).shape == (128,1)
assert all(vector2array(C).flatten() == C)
n = np.random.randint(50,500)
D = np.random.rand(n)
assert vector2array(D).shape == (n,1)
assert np.all(vector2array(D).flatten() == D)

We make some new data to work on:

In [132]:
np.random.seed(38293804)
A35 = np.random.randint(1,10,size=(3,5))
print(A35)

v5 = np.array([1,2,3,4,5])
print(v5)

v3 = np.array([1,2,3])
print(v3)

[[2 9 5 7 2]
 [4 3 4 2 7]
 [2 1 8 2 3]]
[1 2 3 4 5]
[1 2 3]


Subtract the (5,) array from each of the rows of A35. **Note there is no need to first duplicate the v5 array to form a (3,5) shaped array**. Note that your function should work for all arrays of size (m,n) and rows of size (n,).

In [133]:
def subtract_row(a, r):
    """Subtract row r from all rows in a"""
    # YOUR CODE HERE
    raise NotImplementedError()

In [134]:
assert np.all(subtract_row(A35, v5) == np.array([[ 1,  7,  2,  3, -3],
       [ 3,  1,  1, -2,  2],
       [ 1, -1,  5, -2, -2]]))

NotImplementedError: 

Subtract the (3,) array v3 from each of the columns of A35.  Note that your function should work for all arrays of size (m,n) and columns of size (m,).

In [ ]:
def subtract_col(a, c):
    # YOUR CODE HERE
    raise NotImplementedError()

In [ ]:
assert np.all( subtract_col(A35, v3) == \
np.array([[ 1,  8,  4,  6,  1],
          [ 2,  1,  2,  0,  5],
          [-1, -2,  5, -1,  0]]))

## Data Matrix and Target Vector

A lot of tasks in Machine Learning start with a data matrix X and target vector y. Everyone of the m rows in X contains n feature values. X thus is an array of shape (m, n). The target vector value y[i] is either an indicator for the class that the object represent in row i of the data matrix belongs to, or it is a real value (e.g. in regression tasks).

In this section we use the Iris data set as an example.

In [ ]:
from sklearn.datasets import load_iris
dataset = load_iris()
X = dataset.data
y = dataset.target

In [ ]:
print(X.shape, y.shape)

The data sets in sklearn are annotated. For instance the meaning of the columns:

In [ ]:
dataset.feature_names

so the first column gives the sepal length, the second column the sepal width, etc. Btw: the Iris data set is a set of measurements on three different types of Irisses. The three types are:

In [ ]:
names = dataset.target_names
print(names)

these different types are encoded with the values 0, 1 and 2 in the target vector y as we can see examing the unique values in the target vector y:

In [ ]:
np.unique(y)

For data sets from sklearn there is often a key DESCR that describes the dataset. In this case:

In [ ]:
print(dataset.DESCR)

In [ ]:
for (features, target) in zip(X,y):
    print(features, names[target])

Calculate the mean value for all 4 columns in the matrix X. Your statement should return an (4,) array M, such that M[0] is the mean of sepal lengths, etc. Now you can use the numpy function mean.

In [ ]:
def means_columns(a):
    # YOUR CODE HERE
    raise NotImplementedError()

In [ ]:
assert np.allclose(means_columns(X), \
           np.array([5.843, 3.057, 3.758, 1.199]), atol=0.005)


Now subtract the mean value from each element in the data array X. I.e. from all elements in the first column you should subtract the mean of the first column. And the same for the other columns. Again you can do this in a one-liner. The result is again a (150,4) array, lets call it Xzm. You can check your answer by calculating the mean of the columns of this column and then you should get zeros of course.

In [ ]:
def zero_mean_columns(a):
    # YOUR CODE HERE
    raise NotImplementedError()

In [ ]:
Xzm = zero_mean_columns(X)
assert np.allclose(means_columns(Xzm), 0, atol=0.005)

Calculate the standard deviations of all colums. Now you can use the std function.

In [ ]:
def stds_columns(a):
    # YOUR CODE HERE
    raise NotImplementedError()

In [ ]:
assert np.allclose(stds_columns(X), \
                np.array([0.825, 0.434, 1.759, 0.760]), 
                atol=0.005)

Finally calculate the Z-score for each of the elements. So for each value in column i first subtract the mean of column i and then divide by the standard deviation of the column i. You are NOT allowed to use the zscore function from scipy.

In [ ]:
def zscore_columns(a):
    # YOUR CODE HERE
    raise NotImplementedError()

In [ ]:
import scipy
assert np.allclose(zscore_columns(X), scipy.stats.zscore(X,axis=0)) 

In this subsection we have calculated the mean and standard deviation of an entire column. In practice it is often nescessary to first select some rows from X and only then calculate of property of the columns.

Calculate the mean of all columns but only for the rows whose target value equals 1. So only for one type of Irisses.

In [ ]:
def means_versicolor(X):
    # YOUR CODE HERE
    raise NotImplementedError()

In [ ]:
assert np.allclose(means_versicolor(X), \
                np.array([5.94, 2.77 , 4.26 , 1.33]),
                atol = 0.005)

## Linear Algebra

In Python 3 the `@` operator for matrix multiplication was introduced. This means that `A @ B` denotes the matrix multiplication of a matrix (array) A of shape (m,n) with a matrix (array) B of shape (n,k).

Python also allows arrays of shape (n,) to be used in matrix multiplications. Depending on the context it depends on whether Python interprets an array with shape (n,) as a matrix of shape (n,1) or (1,n).

Below some examples are given.

In [ ]:
np.random.seed(324893485)
A = np.random.randint(1,10,size=(3,4))
x = np.random.randint(1,10,size=(4,))
y = np.random.randint(1,10,size=(3,))

In [ ]:
A @ x

In [ ]:
# A @ y  # this does not work, try it yourself

In [ ]:
y @ A

In [ ]:
# x @ A  # this does not work, try it yourself

In [ ]:
x @ x

In [ ]:
vector2array(x) @ vector2array(x).T

In [ ]:
np.outer(x, x)

So nothing for you to do here except note that an array of shape (n,) can be used as either row vector of column vector in a vector-matrix or matrix-vector multiplication respectively.

Note that numpy provides a class 'matrix'

In [ ]:
M = np.matrix(A)
x_col = x[:, np.newaxis]
M * x_col

I strongly advise not to use the matrix class, again: <span style="color:red"> DO NOT USE THE MATRIX CLASS</span>, but it is good to know in case you see it in someone else's code. With Python 3's @ operator for matrix multiplication there is really no need anymore for the matrix class (IMHO).
